### PR TITLE
Parallelize sending messages.

### PR DESCRIPTION
**Pull request by gelfand**

### CODE REVIEW

**Review by battlmonstr — CHANGES_REQUESTED** [review]
Hi. It might be a good change, but there's no description.
Please add a description answering: why is it needed? why is it making things faster/better?

Also could you explain why this was not working before? 
To me it looks like FuturesUnordered was already doing it in parallel
( see https://docs.rs/futures-util/0.3.21/futures_util/stream/struct.FuturesUnordered.html )

**Comment by battlmonstr** [comment]
> > FuturesUnordered was already doing it in parallel
> 
> its not.

please explain

**Comment by gelfand** [comment]
> > > FuturesUnordered was already doing it in parallel
> > 
> > 
> > its not.
> 
> please explain

futures aren't run in parallel, they are polled concurrently, but not parallel.

**Comment by vorot93** [comment]
@battlmonstr `FuturesUnordered` gets containing futures to be polled concurrently, however in order to spread them across CPU cores, they need to be run in separate tokio tasks.

**Comment by battlmonstr** [comment]
@gelfand @vorot93 I might be a dummy or there's some misunderstanding.

In my mind tokio::spawn also runs concurrently.
From https://docs.rs/tokio/1.16.1/tokio/fn.spawn.html :
> Spawning a task enables the task to execute *concurrently* to other tasks.

My understanding of FuturesUnordered is that it is similar to `tokio::select!`: all of the provided futures are polled without any order concurrently and independently. The 2nd future might end before the 1st, and it is immediately returned in the stream of results. The stream ends when all of them are ready. So I wonder how is that different from the new code?

**Comment by vorot93** [comment]
@battlmonstr `tokio::spawn`-ed tasks can be polled by several threads in parallel, while `FuturesUnordered` futures are confined to current task - and thus to only one at any given time.

**Pull request closed without merging**
